# This is a simple GoReleaser config for building and releasing the calc binary
# See https://goreleaser.com/customization/ for more options

project_name: calc

dist: dist

builds:
  - id: calc
    main: ./cmd/calc/main.go
    binary: calc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: -s -w

archives:
  - id: calc-archive
    builds: [calc]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - "calc"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: amjadjibon
    name: calc-go

git:
  tag_sort: semver

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

