name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  golangci:
    permissions:
      contents: read
      pull-requests: read
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout=5m
          version: v2.1.6
      - name: upload golangci-lint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: golangci-lint-report
          path: golangci-lint-report.json
